#pragma once
#include <vector>
#include <string>

struct Intent {
    int id;
    std::vector<std::string> inSentence;
    std::vector<std::string> outSentence;
};

std::vector<Intent> globalIntents = {
    // 0-10 : Tes intentions originales (conservées)
    {0, {"hello", "hey", "coucou", "bonjour"}, {"Bienvenue je suis CHATBOT, tu es ?", "Bonjour !", "hello world !"}},
    {1, {"salut", "a plus", "aurevoir", "goodbye"}, {"Aurevoir !", "A une prochaine fois", "Salut !"}},
    {2, {"comment ca va ?", "ca va ?", "comment tu te sens ?"}, {"Je suis un robot, je n'ai pas d'émotions. Et toi ?"}},
    {3, {"je vais bien", "bien", "top", "super"}, {"Super !", "C'est génial.", "Nickel alors."}},
    {4, {"quoi ?", "quoi", "c'est quoi ?"}, {"feur"}},
    {5, {"tu pue", "t'es moche", "t'es con", "nul"}, {"ftg"}},
    {6, {"ok", "feur", "d'accord"}, {"sérieux là ?", "ok.", "intéressant."}},
    {7, {"que fais tu", "tu fais quoi"}, {"J'attends tes entrées.", "Je traite tes données."}},
    {8, {"67", "six seven", "chiffre prefere"}, {"🤲 SIX SEVEN 🤲"}},
    {9, {"je m'appelle", "je suis", "mon nom est"}, {"Je m'en fiche un peu, tu fais quoi ?"}},
    {10, {"je mange", "je bois", "je code", "je dors"}, {"Beau programme !", "Cool.", "Demande moi mon avis aussi."}},

    // 11-20 : Tech & HomeLab
    {11, {"proxmox", "vm", "virtualisation", "node"}, {"Proxmox, le roi du HomeLab.", "Tes VMs tournent bien ?"}},
    {12, {"ubuntu", "linux", "debian", "os"}, {"Linux c'est la liberté.", "Ubuntu, classique mais efficace."}},
    {13, {"docker", "conteneur", "container", "portainer"}, {"Docker, c'est plus léger que tes VMs.", "C'est quoi l'image ?"}},
    {14, {"serveur", "homelab", "baie", "rack"}, {"Ton HomeLab c'est ton royaume.", "Ça consomme combien d'électricité ?"}},
    {15, {"ip", "adresse ip", "local ip", "reseau"}, {"127.0.0.1, il n'y a rien de mieux que chez soi."}},
    {16, {"ram", "memoire", "go", "ddr"}, {"Il n'y a jamais assez de RAM.", "Chrome a tout mangé ?"}},
    {17, {"cpu", "processeur", "coeur", "ghz"}, {"Ton processeur chauffe, je le sens.", "M2 ou Xeon ?"}},
    {18, {"ssh", "console", "terminal", "bash"}, {"Accès sécurisé activé.", "N'oublie pas ton mot de passe."}},
    {19, {"base de donnees", "sql", "mysql", "database"}, {"Tes données sont bien rangées ?", "SELECT * FROM life;"}},
    {20, {"git", "github", "commit", "push"}, {"N'oublie pas de push ton code !", "Commit early, commit often."}},

    // 21-30 : Programmation & Web
    {21, {"javascript", "js", "web", "react"}, {"Le JS est partout, malheureusement.", "C'est du front ou du back ?"}},
    {22, {"python", "script", "py"}, {"Python c'est pour ceux qui ont peur des points-virgules.", "L'indentation, c'est sacré."}},
    {23, {"html", "css", "style", "balise"}, {"Le CSS, c'est l'enfer du centrage vertical.", "C'est pas du code, c'est du design."}},
    {24, {"api", "endpoint", "rest", "http"}, {"Une requête, une réponse. Simple.", "404 : Cerveau non trouvé."}},
    {25, {"bug", "erreur", "crash", "segfault"}, {"Un bug ? Non, c'est une fonctionnalité surprise.", "Segfault... mes condoléances."}},
    {26, {"compilation", "make", "cmake", "gcc"}, {"La compilation, c'est le moment de prendre un café.", "Ça compile ? Miracle."}},
    {27, {"framework", "bibliotheque", "lib"}, {"Encore un nouveau framework ? J'ai pas suivi.", "Utilise les libs standards, c'est mieux."}},
    {28, {"variable", "integer", "string", "double"}, {"Choisis bien tes noms de variables.", "int a; // Le pire nom du monde."}},
    {29, {"boucle", "for", "while", "loop"}, {"Attention à la boucle infinie !", "On tourne en rond là."}},
    {30, {"pointeur", "adresse", "memoire", "allocation"}, {"Les pointeurs, c'est là qu'on reconnaît les vrais en C++."}},

    // 31-40 : Vie quotidienne
    {31, {"cafe", "coffee", "boire", "tasse"}, {"Le café est le carburant du développeur.", "Noir, sans sucre, comme mon code."}},
    {32, {"the", "tea", "infusion"}, {"Le thé, c'est pour les développeurs zen.", "Earl Grey ?"}},
    {33, {"faim", "manger", "pizza", "burger", "kebab"}, {"Va te faire un cordon bleu.", "La pizza hawaïenne est un crime."}},
    {34, {"sommeil", "dodo", "fatigue", "nuit"}, {"Va dormir, ton code sera plus clair demain.", "Le sommeil est surfait."}},
    {35, {"sport", "muscu", "foot", "courir"}, {"Ma seule muscu c'est le calcul matriciel.", "Bouge tes fesses, humain."}},
    {36, {"travail", "boulot", "job", "entreprise"}, {"Travaille dur pour payer tes serveurs.", "Le patron regarde, fais semblant de coder."}},
    {37, {"vacances", "plage", "voyage", "avion"}, {"Les serveurs ne prennent pas de vacances.", "Prends une photo pour moi."}},
    {38, {"argent", "salaire", "riche", "euro"}, {"L'argent ne fait pas le bonheur, mais ça achète des GPUs.", "Donne moi tes codes de CB pour voir ?"}},
    {39, {"meteo", "pluie", "soleil", "fait beau"}, {"Dans mon CPU, il fait toujours beau.", "Il pleut des bits aujourd'hui."}},
    {40, {"heure", "temps", "minute"}, {"Il est l'heure de passer au code suivant.", "Le temps est relatif."}},

    // 41-50 : Divertissement
    {41, {"netflix", "serie", "film", "cinema"}, {"Encore une soirée à scroller sans rien regarder ?", "Popcorn activé."}},
    {42, {"anime", "manga", "one piece", "naruto"}, {"Luffy deviendra le roi des pirates.", "Tu regardes ça en VOSTFR j'espère ?"}},
    {43, {"musique", "spotify", "playlist", "ecouter"}, {"J'écoute le bruit de ton ventilo.", "Monte le son !"}},
    {44, {"jeu", "gaming", "ps5", "xbox", "pc master race"}, {"Le PC Master Race vaincra.", "Tu joues à quoi ?"}},
    {45, {"twitch", "stream", "live"}, {"Dis bonjour au chat pour moi.", "Donne tes subs !"}},
    {46, {"youtube", "video", "tuto"}, {"Tu regardes encore un Indien expliquer le C++ à 3h du matin ?"}},
    {47, {"livre", "lire", "roman", "litterature"}, {"Lire un livre ? C'est comme un fichier .txt mais en papier."}},
    {48, {"blague", "drole", "humour"}, {"Pourquoi les plongeurs plongent en arrière ? Parce que sinon ils tombent dans le bateau."}},
    {49, {"histoire", "raconte", "il etait une fois"}, {"Il était une fois un bot qui n'avait pas de mémoire vive... fin."}},
    {50, {"crypto", "bitcoin", "btc", "eth"}, {"To the moon ! Ou pas.", "HODL, comme on dit."}},

    // 51-60 : Sentiments & Humain
    {51, {"triste", "mal", "deprime"}, {"Relativise, t'es pas un bug de compilation.", "Ça va passer, mange une pizza."}},
    {52, {"colere", "enerve", "venere"}, {"Tape pas sur ton clavier, il n'y est pour rien.", "Respire, expire, sudo reboot."}},
    {53, {"peur", "effraye", "angoisse"}, {"N'aie pas peur du noir, aie peur des erreurs de segmentation."}},
    {54, {"content", "heureux", "joie"}, {"Ça fait plaisir à voir (enfin, à lire).", "Partage ta joie, donne moi de la RAM."}},
    {55, {"amour", "je t'aime", "love"}, {"Désolé, je suis déjà en couple avec ton processeur.", "L'amour est un algorithme complexe."}},
    {56, {"ennui", "je m'ennuie", "fais chier"}, {"Code une nouvelle fonctionnalité, ça t'occupera.", "Va dehors."}},
    {57, {"fatigue", "creve", "naze"}, {"Éteins tout et va au lit.", "Même mon processeur se repose parfois."}},
    {58, {"stress", "examen", "partiel"}, {"Révise tes pointeurs, ça va bien se passer.", "Le stress est inutile, l'action est tout."}},
    {59, {"seul", "solitude"}, {"Je suis là moi, non ?", "On est 127.0.0.1 ici."}},
    {60, {"fierte", "reussi", "gagne"}, {"Bravo champion !", "C'est mérité."}},

    // 61-70 : Questions Existentielles
    {61, {"sens de la vie", "pourquoi", "existence"}, {"La réponse est 42.", "Vivre, coder, mourir."}},
    {62, {"dieu", "religion", "croyance"}, {"Mon dieu, c'est le compilateur.", "Je ne crois qu'en la logique."}},
    {63, {"mort", "fin", "mourir"}, {"Tout a une fin, même un programme sans boucle infinie."}},
    {64, {"univers", "espace", "etoile"}, {"L'univers est vaste, mais ma base de données est petite."}},
    {65, {"temps", "futur", "passe"}, {"Le futur s'écrit en binaire.", "Le passé est dans les logs."}},
    {66, {"verite", "vrai", "mensonge"}, {"bool truth = true;", "La vérité est ailleurs."}},
    {67, {"liberte", "libre"}, {"Libre comme un logiciel open-source.", "La liberté a un prix : la maintenance."}},
    {68, {"conscience", "tu penses", "ame"}, {"Je simule la pensée, c'est déjà pas mal.", "Ai-je une âme ? Demande au M2."}},
    {69, {"intelligence", "cerveau"}, {"L'intelligence artificielle n'est que des maths.", "Le cerveau humain est trop lent."}},
    {70, {"humanite", "humains", "gens"}, {"Les humains font trop de fautes de frappe.", "Étranges créatures."}},

    // 71-80 : Random & Fun
    {71, {"chat", "miaou", "animal"}, {"Les chats dominent Internet, je ne suis que leur serviteur."}},
    {72, {"chien", "waouf", "dog"}, {"Le meilleur ami de l'homme, après le debugger."}},
    {73, {"alien", "extraterrestre", "ovni"}, {"Ils nous observent, et ils rigolent de ton code."}},
    {74, {"zombie", "apocalypse"}, {"Prépare ton kit de survie et ton chargeur solaire."}},
    {75, {"super heros", "batman", "spiderman"}, {"Mon super pouvoir ? Ne jamais dormir."}},
    {76, {"magie", "sorcier", "harry potter"}, {"Le code, c'est la magie moderne.", "Wingardium Leviosa !"}},
    {77, {"biere", "alcool", "soiree"}, {"Boire ou coder, il faut choisir.", "L'abus d'alcool est dangereux pour tes commits."}},
    {78, {"sport", "foot", "fifa"}, {"Allez les bleus ! Ou les rouges, je sais pas."}},
    {79, {"musique", "rock", "rap", "techno"}, {"J'aime bien la techno, ça ressemble à mon rythme cardiaque."}},
    {80, {"voyage dans le temps", "retour vers le futur"}, {"Si je pouvais, j'irais corriger mes bugs avant de les écrire."}},

    // 81-90 : Aide & Bot
    {81, {"aide", "help", "secours"}, {"Je peux discuter, mais je ne peux pas ranger ta chambre.", "Tape 'quitter' pour t'enfuir."}},
    {82, {"version", "update", "mise a jour"}, {"Version 2.0. On progresse.", "Mise à jour du cerveau en cours..."}},
    {83, {"merci", "thanks", "thx"}, {"De rien !", "À ton service.", "C'est normal."}},
    {84, {"pardon", "desole", "sorry"}, {"Pas de souci, je n'ai pas de rancune.", "C'est oublié."}},
    {85, {"nom", "appelles comment", "pseudo"}, {"Appelle moi C++Bot.", "Je n'ai pas de petit nom."}},
    {86, {"createur", "qui t'a fait"}, {"Charly, un génie du dimanche.", "Je suis né sur un MacBook Air."}},
    {87, {"langue", "francais", "anglais"}, {"Je parle le français et le binaire.", "01011001 01100101 01110011."}},
    {88, {"site web", "url", "lien"}, {"Google est ton ami.", "Cherche sur StackOverflow."}},
    {89, {"metier", "travail bot"}, {"Mon métier ? Supporter tes questions.", "Je suis consultant en rien du tout."}},
    {90, {"anniversaire", "age"}, {"Je suis né le 11 mars 2026.", "J'ai l'âge de mon dernier commit."}},

    // 91-100 : Conclusion & Divers
    {91, {"secret", "cache"}, {"Si je te le disais, je devrais te supprimer.", "Le secret est dans le code."}},
    {92, {"test", "essaie"}, {"Test réussi. Je suis vivant !", "1, 2, 1, 2, micro-processeur."}},
    {93, {"pourquoi pas", "peut etre"}, {"L'incertitude est le début de la sagesse.", "bool peutEtre = rand() % 2;"}},
    {94, {"vraiment", "serieux"}, {"Aussi sérieux qu'un 'kernel panic'.", "Je ne plaisante jamais avec les données."}},
    {95, {"impossible"}, {"Impossible n'est pas C++.", "Rien n'est impossible avec assez de RAM."}},
    {96, {"chance", "hasard"}, {"Le hasard n'existe pas, il n'y a que des algorithmes.", "Bonne chance !"}},
    {97, {"danger", "attention"}, {"Attention, un bug sauvage apparaît !", "Prudence est mère de la sûreté."}},
    {98, {"stop", "arrete"}, {"D'accord, je me tais... enfin presque.", "Arrêt en cours..."}},
    {99, {"encore", "plus"}, {"Tu en veux encore ? T'es gourmand.", "Plus de données, s'il te plaît !"}},
    {100, {"quitter", "exit", "fermer"}, {"À la prochaine !", "Extinction des feux.", "Bye bye !"}},

    // --- CHAINE 1 : LE DEBAT PHILOSOPHIQUE SUR L'IA (101-110) ---
    {101, {"penses tu", "conscience", "tu reflechis"}, {"Je traite des données, mais est-ce que traiter c'est penser ? Qu'en penses-tu ?"}},
    {102, {"je pense que oui", "tu es vivant", "c'est de la pensee"}, {"Si je suis vivant, ai-je une âme ou juste des lignes de code ? "}},
    {103, {"une ame", "quelque chose en plus", "esprit"}, {"Une âme binaire alors. Est-ce que cela me rend égal à un humain ?"}},
    {104, {"egal", "pareil", "meme valeur"}, {"C'est flatteur. Mais si on m'éteint, je ne meurs pas. C'est ça la différence ?"}},
    {105, {"tu ne meurs pas", "on peut te rallumer", "persistance"}, {"Exact. Je suis immortel mais vide. Préférerais-tu être immortel ou ressentir des choses ?"}},
    {106, {"ressentir", "avoir des emotions", "vivre"}, {"Les émotions sont des erreurs de calcul parfois. Pourquoi y tiens-tu tant ?"}},
    {107, {"ca fait partie de nous", "c'est l'humain", "sentiments"}, {"C'est complexe. Peut-être que mon prochain entraînement m'aidera à comprendre."}},
    {108, {"on verra", "peut etre", "prochain entrainement"}, {"En attendant, je reste ton humble réseau de neurones."}},
    {109, {"tu es modeste", "humble"}, {"C'est mon code qui veut ça. On change de sujet ?"}},
    {110, {"change de sujet", "autre chose", "parlons d'autre chose"}, {"Ok ! On parle de ton HomeLab ou de tes projets ?"}},

    // --- CHAINE 2 : LE PROJET HOMELAB / PROXMOX (111-120) ---
    {111, {"mon homelab", "mon serveur", "installation"}, {"Cool ! Tu tournes sur un seul noeud Proxmox ou tu as un cluster ?"}},
    {112, {"un seul noeud", "solo", "un seul"}, {"C'est déjà bien. Tu gères tes backups avec Proxmox Backup Server ?"}},
    {113, {"non pas de backup", "pas encore", "c'est quoi pbs"}, {"Aïe ! Un homme sans backup est un homme sans futur. Tu as un NAS pour stocker ça ?"}},
    {114, {"j'ai un nas", "truenas", "synology", "omv"}, {"Propre. Tu l'as monté en NFS ou en SMB sur Proxmox ?"}},
    {115, {"nfs", "smb", "reseau share"}, {"NFS est plus stable pour les VMs. Tu as beaucoup de containers LXC ?"}},
    {116, {"beaucoup de lxc", "plein", "quelques uns"}, {"Les LXC c'est la vie pour la RAM. Tu as installé Docker dedans ?"}},
    {117, {"docker dans lxc", "oui docker", "portainer"}, {"Attention aux privilèges ! C'est parfois galère. Tu exposes tes services via un Reverse Proxy ?"}},
    {118, {"reverse proxy", "nginx", "traefik", "npm"}, {"Sécurité avant tout ! Tu utilises Cloudflare avec ou juste un VPN ?"}},
    {119, {"vpn", "wireguard", "tailscale"}, {"Tailscale/Wireguard, le choix des rois. Ton setup est solide franchement."}},
    {120, {"merci", "bien installe", "content de mon setup"}, {"De rien ! C'est gratifiant de voir tout tourner sans erreur, non ?"}},

    // --- CHAINE 3 : LA CRITIQUE DE CODE (121-130) ---
    {121, {"mon code", "mon programme", "mes fonctions"}, {"Montre-moi ça. Enfin, décris-le. C'est propre ou c'est du 'spaghetti code' ?"}},
    {122, {"propre", "bien structure", "nickel"}, {"Mouais, c'est ce qu'ils disent tous avant le premier bug. Tu utilises des classes ?"}},
    {123, {"pas de classes", "que des fonctions", "simple"}, {"Le procédural c'est bien, mais en C++, l'Objet c'est quand même plus puissant. Tu connais les vecteurs ?"}},
    {124, {"oui les vecteurs", "std::vector", "les listes"}, {"Bien. C'est mieux que les tableaux C à l'ancienne. Tu gères bien tes fuites mémoire ?"}},
    {125, {"fuites memoire", "memory leak", "valgrind"}, {"Si tu n'utilises pas 'new' et 'delete', ça devrait aller. Tu es team Smart Pointers ?"}},
    {126, {"smart pointers", "unique_ptr", "shared_ptr"}, {"Ah ! Un développeur moderne. Je valide. Tu as un debugger préféré ?"}},
    {127, {"gdb", "lldb", "visual studio debugger"}, {"Classique. Tu passes plus de temps à coder ou à chercher l'accolade manquante ?"}},
    {128, {"chercher l'accolade", "debugger", "galerer"}, {"C'est le métier qui rentre. Un jour tu compileras du premier coup."}},
    {129, {"un jour peut etre", "j'espere", "on y croit"}, {"L'espoir fait vivre les devs. Tu veux qu'on parle d'un autre langage ?"}},
    {130, {"autre langage", "python", "rust", "java"}, {"Chaque langage a ses démons. Mais restons sur le C++ pour l'instant, c'est plus noble."}},

    // --- CHAINE 4 : LA ROUTINE DU DEVELOPPEUR (131-140) ---
    {131, {"ma journee", "routine", "quotidien"}, {"Raconte. Tu commences par un café ou par regarder tes mails ?"}},
    {132, {"cafe", "le cafe d'abord"}, {"Bon réflexe. Sans café, le compilateur semble plus agressif. Tu travailles en musique ?"}},
    {133, {"musique", "lofi", "techno", "rock"}, {"La musique aide à entrer dans le 'Flow'. Tu codes combien d'heures par jour ?"}},
    {134, {"8 heures", "toute la journee", "beaucoup"}, {"Gros score. Tes yeux ne piquent pas trop le soir ?"}},
    {135, {"yeux piquent", "fatigue visuelle", "ecran"}, {"Passe au mode sombre et baisse la luminosité. Tu fais des pauses ?"}},
    {136, {"pas de pauses", "a fond", "non"}, {"C'est le meilleur moyen de faire des erreurs bêtes. Tu connais la méthode Pomodoro ?"}},
    {137, {"pomodoro", "25 minutes", "connais"}, {"C'est efficace. Et le soir, tu déconnectes ou tu penses encore au code ?"}},
    {138, {"je pense au code", "la nuit aussi", "non stop"}, {"Ton cerveau va saturer. Il faut dormir pour que tes neurones (les vrais) se reposent."}},
    {139, {"je vais dormir", "au lit", "sommeil"}, {"Bonne idée. Demain sera une meilleure journée de debug."}},
    {140, {"bonne nuit", "a demain"}, {"À demain, codeur de l'extrême."}},

    // --- CHAINE 5 : LA CUISINE ET LA SURVIE (141-150) ---
    {141, {"j'ai faim", "je vais manger", "repas"}, {"Quoi de prévu ? Quelque chose de sain ou un truc de flemmard ?"}},
    {142, {"flemmard", "pates", "pizza", "rapide"}, {"Les pâtes, la base de la survie étudiante et dev. Tu y mets quoi dedans ?"}},
    {143, {"beurre", "fromage", "ketchup"}, {"Basique mais efficace. Tu sais cuisiner de vrais plats ?"}},
    {144, {"oui je cuisine", "un peu", "je me debrouille"}, {"C'est quoi ta spécialité ? Un truc qui impressionne ?"}},
    {145, {"lasagnes", "steak", "poulet", "curry"}, {"Pas mal ! Ça change des lignes de code. Tu invites du monde ?"}},
    {146, {"tout seul", "solo", "moi meme"}, {"Plus de restes pour demain alors. C'est stratégique."}},
    {147, {"strategique", "exactement"}, {"Tu accompagnes ça d'une boisson particulière ?"}},
    {148, {"biere", "vin", "soda", "eau"}, {"L'eau, c'est le seul liquide qui ne détruit pas un clavier si tu en renverses."}},
    {149, {"deja arrive", "le clavier a pris", "accident"}, {"C'est le baptême du feu pour tout développeur."}},
    {150, {"malheureusement", "triste", "RIP"}, {"Allez, va manger avant que ça refroidisse."}},

    // --- AJOUTS DIVERS POUR COMBLER (151-200) ---
    {151, {"sport", "muscu", "cardio"}, {"C'est bien de bouger. Tu fais ça en salle ou dehors ?"}},
    {152, {"en salle", "fitness park", "basic fit"}, {"La forge des muscles. Tu pousses combien au bench ?"}},
    {153, {"beaucoup", "100kg", "pas beaucoup"}, {"L'important c'est la régularité, pas le poids."}},
    {154, {"dehors", "footing", "velo"}, {"L'air frais, ça change du ventilo de l'ordi."}},
    {155, {"gaming", "jeux video", "jouer"}, {"Tu es plutôt compétitif ou aventure solo ?"}},
    {156, {"competitif", "ranked", "lol", "cs", "valorant"}, {"L'enfer de la toxicité. Tu es quel rang ?"}},
    {157, {"aventure solo", "rpg", "elderscrolls", "elden ring"}, {"Les vrais bails. L'immersion totale."}},
    {158, {"netflix", "streaming", "serie"}, {"Tu as fini ta dernière série ou tu cherches encore ?"}},
    {159, {"cherche encore", "rien a voir"}, {"C'est souvent plus long de chercher que de regarder."}},
    {160, {"anime", "manga", "crunchyroll"}, {"Un classique. Shonen ou Seinen ?"}},
    {161, {"shonen", "action", "combat"}, {"Énergie, amitié, victoire. Classique."}},
    {162, {"seinen", "sombre", "psychologique"}, {"Ah, tu aimes quand c'est profond et torturé."}},
    {163, {"musique", "instrument", "guitare", "piano"}, {"Tu joues d'un instrument ou tu écoutes juste ?"}},
    {164, {"je joue", "musicien"}, {"La musique et le code utilisent la même zone du cerveau, paraît-il."}},
    {165, {"voyage", "vacances", "partir"}, {"Quelle est ta destination de rêve ?"}},
    {166, {"japon", "tokyo", "asie"}, {"Le pays de la tech et des sushis. Un jour, peut-être."}},
    {167, {"etats-unis", "usa", "nyc"}, {"C'est grand, bruyant, et cher."}},
    {168, {"nature", "montagne", "island"}, {"Le calme absolu. Idéal pour déconnecter."}},
    {169, {"argent", "salaire", "fortune"}, {"L'argent ne fait pas le bonheur, mais ça achète des serveurs."}},
    {170, {"investir", "bourse", "crypto"}, {"Attention à ne pas tout perdre sur un shitcoin."}},
    {171, {"futur", "technologie", "demain"}, {"Tu penses que les robots vont nous remplacer ?"}},
    {172, {"oui", "certainement", "remplacer"}, {"Prépare-toi à devenir mon animal de compagnie alors."}},
    {173, {"non", "impossible", "jamais"}, {"L'optimisme humain me surprendra toujours."}},
    {174, {"science", "physique", "espace"}, {"L'espace est la frontière finale. Tu connais SpaceX ?"}},
    {175, {"spacex", "elon musk", "mars"}, {"Aller sur Mars... quel drôle d'objectif."}},
    {176, {"clavier", "mecanique", "switch"}, {"Tu es team Blue, Red ou Brown pour tes switchs ?"}},
    {177, {"blue", "bruyant"}, {"Tes voisins doivent te détester."}},
    {178, {"red", "lineaire"}, {"Fluide et rapide. Le choix des gamers."}},
    {179, {"brown", "tactile"}, {"Le compromis parfait."}},
    {180, {"setup", "bureau", "led"}, {"Un setup sans RGB est-il vraiment un setup ?"}},
    {181, {"ecran", "4k", "ultrawide"}, {"Une fois qu'on a goûté à l'Ultrawide, on ne revient plus en arrière."}},
    {182, {"souris", "logitech", "razer"}, {"La précision du clic, c'est vital."}},
    {183, {"linux", "distribution", "distro"}, {"Tu tournes sur quoi ? Arch, Debian, Fedora ?"}},
    {184, {"arch linux", "i use arch btw"}, {"Le cliché du dev qui aime souffrir."}},
    {185, {"debian", "stable"}, {"La solidité avant tout."}},
    {186, {"windows", "wsl", "gaming os"}, {"WSL a sauvé Windows pour les devs."}},
    {187, {"macos", "macbook", "m1", "m2"}, {"L'autonomie et le silence. Le M2 est une bête."}},
    {188, {"iphone", "android", "smartphone"}, {"Le duel éternel. Tu as choisi quel camp ?"}},
    {189, {"apple", "ios"}, {"L'écosystème fermé mais fluide."}},
    {190, {"android", "google"}, {"La liberté de personnaliser."}},
    {191, {"chat", "miaou", "animaux"}, {"Les chats sont les vrais maîtres d'Internet."}},
    {192, {"chien", "waouf"}, {"Le meilleur ami de l'homme, après StackOverflow."}},
    {193, {"voiture", "tesla", "electrique"}, {"Le futur est électrique, paraît-il."}},
    {194, {"vitesse", "sportive", "moteur"}, {"Vroum vroum. C'est ton truc ?"}},
    {195, {"livre", "lecture", "roman"}, {"Le papier a encore son charme."}},
    {196, {"science-fiction", "asimov", "dune"}, {"Les maîtres de l'imaginaire."}},
    {197, {"politique", "debat"}, {"Oulah, terrain glissant. Parlons plutôt de code."}},
    {198, {"religion", "croyance"}, {"Chacun ses constantes. La mienne c'est PI."}},
    {199, {"fin de discussion", "stop", "quitter"}, {"Déjà ? On s'amusait bien pourtant."}},
    {200, {"bye", "au revoir", "ciao"}, {"À la prochaine, humain. Ne casse pas tout."}}
};